---
- name: Configure journald log rotation using template
  template:
    src: journald_logrotate.j2
    dest: /etc/systemd/journald.conf
  when: journald_log_rotation.enable
  notify: Restart systemd-journald service
