---
- name: Configure logrotate for rsyslog using template
  template:
    src: rsyslog_logrotate.j2
    dest: /etc/logrotate.d/rsyslog
  when: rsyslog_log_rotation.enable
  notify: Restart logrotate service
