---
# Install & configure packages on Debian/Ubuntu, driven by defaults/main.yml only.

- block:
    #####################################################################
    # 0) Sanitize HashiCorp APT repo to avoid Signed-By conflicts
    #####################################################################
    - name: Ensure /etc/apt/keyrings exists (new standard path)
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: true

    # 删除可能遗留的旧源（list）与旧 deb822（sources），保持只有一种格式
    - name: Remove legacy HashiCorp .list repo (if any)
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/hashicorp.list
        state: absent
      become: true

    - name: Remove legacy HashiCorp deb822 .sources (to re-add cleanly)
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/hashicorp.sources
        state: absent
      become: true

    # 删除历史上可能存在的不同 keyring 路径，避免 APT 仍引用它们
    - name: Remove legacy keyring in /usr/share/keyrings (if any)
      ansible.builtin.file:
        path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
        state: absent
      become: true

    # 统一用 /etc/apt/keyrings/hashicorp.gpg；先拿 ASCII，再 dearmor
    - name: Fetch HashiCorp ASCII key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /etc/apt/keyrings/hashicorp.asc
        mode: '0644'
      when: enable_hashicorp_repo | default(true) | bool
      become: true

    - name: Dearmor HashiCorp key to .gpg
      ansible.builtin.command:
        cmd: "gpg --dearmor -o /etc/apt/keyrings/hashicorp.gpg /etc/apt/keyrings/hashicorp.asc"
        creates: /etc/apt/keyrings/hashicorp.gpg
      when: enable_hashicorp_repo | default(true) | bool
      become: true

    - name: Ensure keyring permissions (world-readable)
      ansible.builtin.file:
        path: /etc/apt/keyrings/hashicorp.gpg
        owner: root
        group: root
        mode: '0644'
        state: file
      when: enable_hashicorp_repo | default(true) | bool
      become: true

    # 只保留 deb822 写法，使用统一的 signed-by 路径
    - name: Add HashiCorp APT repo via deb822 (clean, unified)
      ansible.builtin.deb822_repository:
        name: hashicorp
        types: [deb]
        uris: ["https://apt.releases.hashicorp.com"]
        suites: ["{{ hashicorp_repo_suite | default(ansible_distribution_release) }}"]
        components: ["main"]
        signed_by: "/etc/apt/keyrings/hashicorp.gpg"
        state: "{{ (enable_hashicorp_repo | default(true) | bool) | ternary('present', 'absent') }}"
      become: true

    #####################################################################
    # 1) Base APT deps  (不在此处触发 update_cache，避免再次读到坏源)
    #####################################################################
    - name: Ensure base APT deps (no update now)
      ansible.builtin.apt:
        name:
          - ca-certificates
          - gnupg
        state: present
        update_cache: false
      become: true

    #####################################################################
    # 2) Ubuntu universe（仅 Ubuntu，且可控开关）
    #####################################################################
    - name: Enable Ubuntu 'universe' component (Ubuntu only)
      ansible.builtin.apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main universe"
        state: present
        filename: "ubuntu-{{ ansible_distribution_release }}-universe"
      when:
        - ansible_facts.distribution == 'Ubuntu'
        - enable_ubuntu_universe | default(true) | bool
      become: true

    #####################################################################
    # 3) 现在再统一 update cache
    #####################################################################
    - name: Update apt cache after repo normalization
      ansible.builtin.apt:
        update_cache: true
      become: true

    #####################################################################
    # 4) 安装包（仅当 enable_install_packages=true）
    #####################################################################
    - name: Install packages (guarded by enable_install_packages)
      ansible.builtin.apt:
        name: "{{ common_packages | default(['vault', 'auditd', 'uidmap', 'fuse-overlayfs']) }}"
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive
        APT_LISTCHANGES_FRONTEND: none
      when: enable_install_packages | bool
      become: true

  when: ansible_facts.os_family == 'Debian'
  tags: [pkgs, baseline]
