- name: Set timezone
  shell: "timedatectl set-timezone Asia/Shanghai"

- name: Set hostname
  shell: "hostname -F /etc/hostname"

- name: update /etc/hostname
  template: src=templates/hostname dest=/etc/hostname owner=root group=root mode=0644 unsafe_writes=yes

- name: Update /etc/hosts
  template: src=templates/hosts dest=/etc/hosts owner=root group=root mode=0644 force=yes unsafe_writes=yes

- name: Run secure_ssh.sh script
  script: files/secure_ssh.sh

- name: "Common | Run on Debian family only"
  when:
    - enable_common | bool
    - ansible_facts.os_family == 'Debian'
  block:
    - name: "Common | Repo & keys"
      ansible.builtin.include_tasks: repo_setup.yml
      when: repo_setup | bool
      tags: [repo, baseline]

    - name: "Common | Packages"
      ansible.builtin.include_tasks: packages.yml
      when: install_packages | bool
      tags: [pkgs, baseline]

#- name: Include GPU Configuration
#  include_tasks: include_gpu.yaml
#  when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")
#  tags: 
#    - k3s
#    - gpu
#    - nvidia

#- name: enable ip_forward
#  shell: 'echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf; echo "net.ipv4.conf.all.proxy_arp = 1" >> /etc/sysctl.conf ; sysctl -p /etc/sysctl.conf'


#- name: Install packages
#  shell: "yum makecache && yum install -y audit container-selinux"
#  when: (ansible_facts['distribution'] != "Ubuntu") or (ansible_facts['distribution'] != "Debian")
