---
# 基础依赖（不在此处 update_cache，避免读取未规范化源）
- name: Ensure base APT deps (no update now)
  ansible.builtin.apt:
    name:
      - ca-certificates
      - gnupg
    state: present
    update_cache: false
  become: true

# 实际安装
- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages | default([]) }}"
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive
    APT_LISTCHANGES_FRONTEND: none
  when: (packages | default([])) | length > 0
  become: true

