- name: Create Prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ prometheus_dir }}"
    - "{{ prometheus_etc }}"
    - "{{ prometheus_data }}"
    - "{{ prometheus_file_sd_dir }}"
  when: inventory_hostname in groups[group]

- name: Ensure prometheus user exists
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false
  when: inventory_hostname in groups[group]

- name: Set Prometheus archive for amd64
  ansible.builtin.set_fact:
    prometheus_tar: "prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    prometheus_src_dir: "prometheus-{{ prometheus_version }}.linux-amd64"
  when:
    - inventory_hostname in groups[group]
    - ansible_architecture in ['x86_64', 'amd64']

- name: Set Prometheus archive for arm64
  ansible.builtin.set_fact:
    prometheus_tar: "prometheus-{{ prometheus_version }}.linux-arm64.tar.gz"
    prometheus_src_dir: "prometheus-{{ prometheus_version }}.linux-arm64"
  when:
    - inventory_hostname in groups[group]
    - ansible_architecture in ['aarch64', 'arm64']

- name: Download Prometheus archive
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_tar }}"
    dest: "/tmp/{{ prometheus_tar }}"
    mode: '0644'
  when: inventory_hostname in groups[group]

- name: Extract Prometheus archive
  ansible.builtin.unarchive:
    src: "/tmp/{{ prometheus_tar }}"
    dest: /tmp
    remote_src: true
    creates: "/tmp/{{ prometheus_src_dir }}"
  when: inventory_hostname in groups[group]

- name: Install Prometheus binaries
  ansible.builtin.copy:
    src: "/tmp/{{ prometheus_src_dir }}/{{ item }}"
    dest: "{{ prometheus_dir }}/{{ item }}"
    mode: '0755'
    remote_src: true
  loop:
    - prometheus
    - promtool
  when: inventory_hostname in groups[group]

- name: Symlink Prometheus binaries
  ansible.builtin.file:
    src: "{{ prometheus_dir }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - prometheus
    - promtool
  when: inventory_hostname in groups[group]

- name: Create default file_sd config
  ansible.builtin.template:
    src: nodes.json.j2
    dest: "{{ prometheus_file_sd_dir }}/nodes.json"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0644'
  when: inventory_hostname in groups[group]

- name: Deploy Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_etc }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0644'
  when: inventory_hostname in groups[group]

- name: Ensure Prometheus ownership
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    recurse: true
  loop:
    - "{{ prometheus_data }}"
    - "{{ prometheus_etc }}"
  when: inventory_hostname in groups[group]

- name: Install Prometheus service
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'
  when: inventory_hostname in groups[group]

- name: Enable and start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: restarted
    daemon_reload: true
  when: inventory_hostname in groups[group]
