---
postgres_db: keycloak
postgres_user: keycloak_user
postgres_password: keycloak_password

keycloak_admin: admin
keycloak_admin_password: admin_password

keycloak_key_store_password: a4h3ljbn
keycloak_trust_store_password: a4h3ljbn

ssl_certificate_path: /etc/ssl/onwalk.net.pem
ssl_certificate_key_path: /etc/ssl/onwalk.net.key
dhparam_path: /etc/ssl/dhparam.pem
