- name: Install sealos CLI
  shell: |
    curl -sL https://raw.githubusercontent.com/labring/sealos/main/scripts/install.sh | bash -s {{ sealos_version }}
  args:
    executable: /bin/bash
  when: inventory_hostname == (ops_host | default(master_ips | first))

- name: Run sealos to create Kubernetes cluster
  shell: |
    sealos run \
      registry.cn-shanghai.aliyuncs.com/labring/kubernetes:{{ sealos_version }} \
      registry.cn-shanghai.aliyuncs.com/labring/cilium:{{ cilium_version }} \
      registry.cn-shanghai.aliyuncs.com/labring/helm:{{ helm_version }} \
      --masters {{ master_ips | join(',') }} \
      --nodes {{ node_ips | join(',') }} \
      --env '{{ sealos_cmd_env }}' \
      --cmd "{{ kubeadm_init_cmd }}"
  args:
    executable: /bin/bash
  when: inventory_hostname == (ops_host | default(master_ips | first))
