- name: Bootstrap Kubernetes cluster with GPU support
  include_tasks: install_cluster.yml

- name: Install NVIDIA GPU drivers
  include_tasks: install_driver.yml

- name: Validate GPU access with test workload
  include_tasks: run_test.yml
