apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stable
  namespace: monitoring
spec:
  interval: 10m
  url: https://charts.onwalk.net/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: observabilityagent
  namespace: monitoring
spec:
  chart:
    spec:
      chart: observabilityagent
      version: "0.1.7"
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: monitoring
  interval: 1m
  values:
    fluent-bit:
      enabled: false
    telegraf:
      enabled: true
      config:
        agent:
          interval: "10s"
          round_interval: true
          metric_batch_size: 1000
          metric_buffer_limit: 10000
          collection_jitter: "0s"
          flush_interval: "10s"
          flush_jitter: "0s"
          precision: ""
          debug: false
          quiet: false
          logfile: ""
          hostname: "$HOSTNAME"
          omit_hostname: true
        processors:
          - enum:
              mapping:
                field: "status"
                dest: "status_code"
                value_mappings:
                  healthy: 1
                  problem: 2
                  critical: 3
        outputs:
          - influxdb:
              urls:
                - "influxdb.svc-dev.ink"
              database: "telegraf"
        inputs:
          - net:
              interfaces: *
          - statsd:
              service_address: ":8125"
              percentiles:
                - 50
                - 95
                - 99
              metric_separator: "_"
              allowed_pending_messages: 10000
              percentile_limit: 1000
    deepflow-agent:
      enabled: true
      deepflowServerNodeIPS:
        - 10.0.1.3
      deepflowK8sClusterID: d-rUJ4CUKMUt
    prometheus:
      enabled: true
      server:
        name: agent
        retention: "30m"
        extraFlags:
        - web.enable-lifecycle
        - enable-feature=expand-external-labels
        remoteWrite:
        - name: remote_prometheus
          url: 'https://prometheus.svc-dev.ink/api/v1/write'
        persistentVolume:
          enabled: false
      alertmanager:
        enabled: false
      prometheus-pushgateway:
        enabled: false
      kube-state-metrics:
        enabled: false
      prometheus-node-exporter:
        enabled: false
    promtail:
      enabled: true
      config:
        clients:
          - url: https://loki.svc-dev.ink/loki/api/v1/push
