apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stable
  namespace: demo-js
spec:
  interval: 1m
  url: https://charts.onwalk.net/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stable
  namespace: demo-js
spec:
  chart:
    spec:
      chart: app
      version: "0.1.1"
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: demo-python
  interval: 1m
  values:
    image:
      repository: artifact.onwalk.net/base/scaffolding-design/javascript-frontend
      tag: "fc998a6d433c45986dc7d51ab62bf7aa48613d62"
    ingress:
      className: "nginx"
