apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stable
  namespace: demo-go
spec:
  interval: 1m
  url: https://charts.onwalk.net/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stable
  namespace: demo-go
spec:
  chart:
    spec:
      chart: app
      version: "0.1.1"
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: demo-go
  interval: 1m
  values:
    image:
      repository: artifact.onwalk.net/base/scaffolding-design/go
      tag: "fe2a0fba3014709b26d8acd75bacb661bf2522a4"
