apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-go
  namespace: demo-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
    spec:
      containers:
      - name: demo-go
        image: artifact.onwalk.net/base/scaffolding-design/go:fe2a0fba3014709b26d8acd75bacb661bf2522a4
        imagePullPolicy: Always
