apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../apps/monitor/flagger/
  - ../../apps/monitor/flagger-loadtester/
  - ../../apps/monitor/loki-stack
  - namespace.yaml
  - helmrepo.yaml
  - observability-agent.yaml
 - ingress-flagger.yaml
#  - prometheus-server-configmap.yaml
#  - alert-rules-patch.yaml
#  - recording-rules-patch.yaml
