apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: observabilityagent
  namespace: monitoring
spec:
  chart:
    spec:
      chart: observabilityagent
      version: "0.1.6"
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: monitoring
  interval: 1m
  values:
    fluent-bit:
      enabled: false
    deepflow-agent:
      enabled: false
    prometheus:
      enabled: false
    promtail:
      enabled: true
      config:
        clients:
          - url: https://data-gateway.svc-dev.ink/loki/api/v1/push
