apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: observabilityagent
  namespace: monitoring
spec:
  chart:
    spec:
      chart: observabilityagent
      version: "0.1.6"
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: monitoring
  interval: 1m
  values:
    deepflow-agent:
      enabled: false
    prometheus:
      enabled: true
      server:
        extraFlags:
        - enable-feature=expand-external-labels
        - web.enable-lifecycle
        remoteWrite:
        - name: remote_prometheus
          url: 'https://prometheus.svc.plus/api/v1/write'
      alertmanager:
        enabled: false
      rometheus-pushgateway:
        enabled: false
    promtail:
      enabled: true
      config:
        clients:
          - url: https://data-gateway.svc.plus/loki/api/v1/push
