apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stable
  namespace: demo-python
spec:
  interval: 1m
  url: https://charts.onwalk.net/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stable
  namespace: demo-python
spec:
  chart:
    spec:
      chart: app
      version: "0.1.1"
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: demo-python
  interval: 1m
  values:
    image:
      repository: artifact.onwalk.net/base/scaffolding-design/python
      tag: "d72ba38f7a3a76b71eb50f00fe46a94497e6ecaa"
