apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  namespace: demo-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-python
  template:
    metadata:
      labels:
        app: demo-python
    spec:
      containers:
      - name: demo-python
        image: artifact.onwalk.net/base/scaffolding-design/python:d72ba38f7a3a76b71eb50f00fe46a94497e6ecaa
        imagePullPolicy: Always
