apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flaggerloadtester
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      version: "0.30.0"
      chart: flagger-loadtester
      sourceRef:
        kind: HelmRepository
        name: flaggerload
        namespace: monitoring
      interval: 1m
