repositories:
- name: stable
  url: https://charts.onwalk.net

templates:
  default: &default
    namespace: itsm-dev
    createNamespace: true
    chart: stable/itsm
    version: 0.1.16

releases:
  - name: itsm-dev
    <<: *default
    set:
    - name: apisix.dashboard.enabled
      value: true
    - name: apisix.dashboard.ingress.enabled
      value: true
    - name: apisix.dashboard.ingress.className
      value: nginx
    - name: apisix.dashboard.ingress.hosts[0].host
      value: apisix-dashboard.onwalk.net
    - name: apisix.dashboard.ingress.hosts[0].paths[0]
      value: '/*'
    - name: apisix.etcd.enabled
      value: true
    - name: etcd-adapter.enabled
      value: false
    - name: novu.web.ingress.enabled
      value: true
    - name: novu.web.ingress.ingressClassName
      value: nginx
    - name: novu.web.ingress.hostname
      value: 'novu.onwalk.net'
    - name: novu.redis.enabled
      value: false
    - name: novu.externalRedis.host
      value: redis.local
    - name: novu.externalRedis.existingSecret
      value: itsm-redis-secret
    - name: novu.mongodb.enabled
      value: false
    - name: novu.externalDatabase.existingSecret
      value: itsm-mongodb-secret-rw
    - name: novu.localstack.enabled
      value: false
    - name: novu.externalS3.existingSecret
      value: itsm-s3-secret-rw
    - name: windmill.databaseUrlSecretName
      value: itsm-postgresql-secret-rw
