apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-ingress-podmonitor
  labels:
    app.kubernetes.io/part-of: nginx
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx
  namespaceSelector:
    matchNames:
      - ingress
  podMetricsEndpoints:
    - port: "9113"
      interval: 30s
      path: /metrics
