apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mysql
  namespace: itsm-dev
spec:
  interval: 1m
  chart:
    spec:
      version: "9.21.2"
      chart: mysql
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: itsm-dev
      interval: 1m
  values:
    enabled: true
    fullnameOverride: mysql
    global:
      imageRegistry: "artifact.onwalk.net/public"
    architecture: standalone
    auth:
      createDatabase: true
      rootPassword: "mysqladmin"
      database: "apisix"
      username: "apisix"
      password: "apisix"
      existingSecret: ""
    primary:
      persistence:
        enabled: true
        size: 8Gi
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 200m
          memory: 400Mi
    secondary:
      replicaCount: 0
