action: 'bootstrap'
cluster:
  name: 'cn-k3s-cluster-1'
  token: 'your_default_token'
  server_disable: "traefik,servicelb"
  datastore_endpoint: "mysql://user:password@tcp(database_url:3306)/k3s"
  registry: "registry.cn-hangzhou.aliyuncs.com"
  data_dir: "/opt/rancher/k3s"
  apiserver_arg: "service-node-port-range=0-50000"
  bind_address: "0.0.0.0"
  tls_san: "cn-k3s-server.svc.plus"
  advertise_address: "8.130.93.47"
  node_ip: "10.254.0.3"
  node_external_ip: "8.130.93.47"
  flannel_iface: "wg0"
  cluster_cidr: "10.42.0.0/16"
  service_cidr: "10.43.0.0/16"
