apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-agent
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2023-12-27T12:13:56Z"
  generation: 2
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prometheus-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 55.5.0
    chart: kube-prometheus-stack-55.5.0
    helm.toolkit.fluxcd.io/name: prometheus-agent
    helm.toolkit.fluxcd.io/namespace: monitoring
    heritage: Helm
    release: prometheus-agent
  name: prometheus-agent-kube-prom-prometheus
  namespace: monitoring
  resourceVersion: "14691"
  uid: 9bf6429e-2ae1-4568-95ee-0e2dc1a4071f
spec:
  externalUrl: http://prometheus-agent-kube-prom-prometheus.monitoring:9090
  hostNetwork: false
  image: artifact.onwalk.net/base/prometheus/prometheus:v2.48.1
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      app.kubernetes.io/component: monitoring
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: prometheus-agent
  remoteWrite:
  - name: remote_prometheus
    url: https://prometheus.demo-dev.ink/api/v1/write
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
  routePrefix: /
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      release: prometheus-agent
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: prometheus-agent-kube-prom-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: prometheus-agent
  shards: 1
  version: v2.48.1
  walCompression: true
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-12-27T13:20:17Z"
    message: ""
    observedGeneration: 2
    reason: ""
    status: "True"
    type: Available
  - lastTransitionTime: "2023-12-27T13:20:17Z"
    message: ""
    observedGeneration: 2
    reason: ""
    status: "True"
    type: Reconciled
  paused: false
  replicas: 1
  shardStatuses:
  - availableReplicas: 1
    replicas: 1
    shardID: "0"
    unavailableReplicas: 0
    updatedReplicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
