apiVersion: v1
kind: Service
metadata:
  name: kustomize-controller-metrics
  namespace: gitops-system
  labels:
    app: kustomize-controller
spec:
  selector:
    app: kustomize-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helm-controller-metrics
  namespace: gitops-system
  labels:
    app: helm-controller
spec:
  selector:
    app: helm-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: source-controller-metrics
  namespace: gitops-system
  labels:
    app: source-controller
spec:
  selector:
    app: source-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
