apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - observability-agent.yaml
  - prometheus-agent-configmap.yaml
patches:
  - prometheus-agent-configmap-patch-fluxcd.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-system
resources:
  - fluxcd-metrics.yaml
