apiVersion: v1
kind: ConfigMap
metadata:
  name: update-nginx-config
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      root {{ .Values.storage.mountPath }};
      index index.html;
      autoindex on;
      location / {
        autoindex_exact_size off;
        autoindex_localtime on;
        try_files $uri $uri/ =404;
      }
    }
