---
postgres_name: postgres
postgres_image: postgres:16.0-bookworm
postgres_db: keycloak
postgres_user: keycloak_user
postgres_password: keycloak_password

keycloak_name: keycloak
keycloak_domain: keycloak.onwalk.net
keycloak_image: bitnami/keycloak:latest
keycloak_admin: admin
keycloak_admin_password: admin_password

nginx_name: nginx
nginx_image: nginx:latest

key_alias: mykey
key_password: your_key_password
keycloak_key_store:
  file: /etc/ssl/keystore.jks
  password: your_key_password
keycloak_trust_store:
  file: /etc/ssl/truststore.jks
  password: your_trust_password

# SSL证书路径和文件名
ca_certificate:
  file: /etc/ssl/onwalk.net.pem
ssl_certificate:
  path: /etc/ssl/
  name: onwalk.net.pem
ssl_certificate_key:
  path: /etc/ssl/
  name: onwalk.net.key

dhparam_path: /etc/ssl/dhparam.pem
