apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: artifact.onwalk.net/base/scaffolding-design/rust:84a66d19f29c20c57127f5c896d00b0b84dcd986
        imagePullPolicy: Always
