apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: itsm-dev
  namespace: itsm-dev
spec:
  interval: 1m
  chart:
    spec:
      version: "0.1.16"
      chart: itsm
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: itsm-dev
      interval: 1m
  values:
    etcd-adapter:
      enabled: true
      mysql:
        host: mysql
        port: 3306
        username: apisix
        password: apisix
        database: apisix
