apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: itsm-dev
  namespace: itsm-dev
spec:
  interval: 1m
  chart:
    spec:
      version: "0.1.15"
      chart: itsm
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: itsm-dev
      interval: 1m
