apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: itsm-dev
  namespace: itsm-dev
spec:
  interval: 1m
  chart:
    spec:
      version: "0.1.16"
      chart: itsm
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: itsm-dev
      interval: 1m
  values:
    novu:
      web:
        ingress:
          enabled: true
          hostname: novu-web.onwalk.net
          ingressClassName: 'nginx'
    apisix:
      dashboard:
        ingress:
          enabled: true
          className: "nginx"
          hosts:
            - host: apisix-dashboard.onwalk.net
              paths:
                - /*
    etcd-adapter:
      enabled: true
      mysql:
        host: mysql
        port: 3306
        username: apisix
        password: apisix
        database: apisix
