apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-c
  namespace: demo-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-c
  template:
    metadata:
      labels:
        app: demo-c
    spec:
      containers:
      - name: demo-c
        image: artifact.onwalk.net/base/scaffolding-design/c:dee1c17b11822997e16e71244b1a1e98fe919688 
        imagePullPolicy: Always
