apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stable
  namespace: demo-c
spec:
  interval: 1m
  url: https://charts.onwalk.net/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cp-app
  namespace: demo-c
spec:
  chart:
    spec:
      chart: app
      version: "0.1.1"
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: demo-c
  interval: 1m
  values:
    image:
      repository: artifact.onwalk.net/base/scaffolding-design/c
      tag: "dee1c17b11822997e16e71244b1a1e98fe919688"
    ingress:
      className: "apisix"
