---
- name: 安装 Docker 和 Docker Compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: 启动并启用 Docker 服务
  systemd:
    name: docker
    enabled: yes
    state: started

- name: 创建所需的目录结构
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/ssl
