repositories:
- name: stable
  url: https://charts.onwalk.net
  username: {{ requiredEnv "ARF_USERNAME" }}
  password: {{ requiredEnv "ARF_PASSWORD" | quote }}

templates:
  default: &default
    namespace: itsm-dev
    createNamespace: true
    chart: stable/app-frontend
    version: 0.1.3

releases:
  - name: itsm-dev
    <<: *default
    set:
    - name: image.repository 
      value: ""
    - name: image.tag 
      value: ""
    - name: service.port 
      value: ""
