repositories:
  - name: stable
    url: https://charts.onwalk.net
    username: {{ requiredEnv "ARF_USERNAME" }}
    password: {{ requiredEnv "ARF_PASSWORD" | quote }}

common:
  namespace: itsm-tools-stg
  createNamespace: false
  chart: stable/app-backend
  version: 0.1.3
  values:
    service:
      type: ClusterIP
      ports:
        - name: http
          port: 8000
          targetPort: http
          protocol: TCP
        - name: grpc
          port: 9000
          targetPort: grpc
          protocol: TCP
    containerPorts:
      - name: http
        port: 8000
        protocol: TCP
      - name: grpc
        port: 9000
        protocol: TCP

releases:
  - name: itsm-ticketing
    <<: {{"{{" }} include "common" . | nindent 4 {{ "}}" }}
    set:
      - name: image.repository
        value: artifact.onwalk.net/itsm/ticketing
      - name: image.tag
        value: 'unknown-fa7fed7'
      - name: volumeMounts
        value:
          - name: ticketing-config
            mountPath: /ticketing/conf
      - name: volumes
        value:
          - name: ticketing-config
            secret:
              secretName: itsm
              defaultMode: 420
              items:
                - key: ticketing.yaml
                  path: config.yaml
