repositories:
  - name: stable
    url: https://charts.onwalk.net

templates:
  defaultIngress: &defaultIngress
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"

environments:
  stage:
    values:
      - ingressHostname: novu-web-stage.onwalk.net
      - resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
  prod:
    values:
      - ingressHostname: novu-web-prod.onwalk.net
      - resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

releases:
  - name: itsm-dev
    namespace: itsm-dev
    chart: stable/itsm
    version: "0.1.16"
    values:
      - novu:
          web:
            ingress:
              enabled: true
              hostname: {{ .Environment.Values.ingressHostname }}
              ingressClassName: 'nginx'
        apisix:
          dashboard:
            ingress:
              enabled: true
              className: "nginx"
              hosts:
                - host: apisix-dashboard.onwalk.net
                  paths:
                    - /*
        etcd-adapter:
          enabled: true
          mysql:
            host: mysql
            port: 3306
            username: apisix
            password: apisix
            database: apisix
        resources: {{ .Environment.Values.resources }}
