apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: itsm-dev
spec:
  interval: 1m
  chart:
    spec:
      version: "14.8.3"
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: itsm-dev
      interval: 1m
  values:
    enabled: true
    nameOverride: "mongodb"
    architecture: standalone
    useStatefulSet: true
    global:
      imageRegistry: ""
    persistence:
      enabled: true
    auth:
      enabled: true
      rootUser: root
      rootPassword: "mongodb"
      usernames:
      - novu
      passwords:
      - novu
      databases:
      - novu-db
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        cpu: "500m"
        memory: "500Mi"
