- name: Install Redis server
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Enable and start Redis service
  systemd:
    name: redis-server
    enabled: yes
    state: started
