apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: itsm-dev
spec:
  interval: 1m
  chart:
    spec:
      version: "0.1.13"
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: itsm-dev
      interval: 1m
  values:
    enabled: true
    fullnameOverride: windmill-postgresql
    global:
      imageRegistry: ""
      postgresql:
        auth:
          postgresPassword: "windmill"
          username: "postgres"
          password: "windmill"
          database: "windmill"
    primary:
      persistence:
        enabled: true
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          cpu: "200m"
          memory: "300Mi"
