apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flagger
  namespace: ingress
spec:
  interval: 1m
  dependsOn:
    - name: flagger
  chart:
    spec:
      version: "1.35.0"
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: ingress
      interval: 1m
  values:
    prometheus:
      install:false
    meshProvider: nginx
    metricsServer: "https://prometheus.svc.ink"
