apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-server
  labels:
    app: homepage-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage-server
  template:
    metadata:
      labels:
        app: homepage-server
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: update-volume
              mountPath: {{ .Values.storage.mountPath }}
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: update-volume
          hostPath:
            path: {{ .Values.storage.hostPath }}
            type: DirectoryOrCreate
        - name: nginx-conf
          configMap:
            name: homepage-nginx-config
