- name: Include apt setup
  import_tasks: apt_setup.yml

- name: Include user setup
  import_tasks: user_setup.yml

- name: Include base packages
  import_tasks: packages.yml

- name: Include GPU configuration
  import_tasks: gpu.yml

- name: Include system configuration
  import_tasks: system_config.yml

- name: Include reboot logic
  import_tasks: reboot.yml

- name: Configure container runtime
  import_tasks: containerd.yml

- name: Configure networking
  import_tasks: network.yml
