- name: Create user
  user:
    name: "{{ username }}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Create SSH directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  with_items:
    - "/home/{{ username }}/.ssh"
    - "/root/.ssh"

- name: Add authorized SSH keys
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_public_keys }}"
  become: yes

- name: Set correct ownership for user home
  file:
    path: "/home/{{ username }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Add user to sudoers
  lineinfile:
    path: /etc/sudoers
    line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
