apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
  namespace: itsm-dev
spec:
  interval: 1m
  chart:
    spec:
      version: "5.0.15"
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: itsm-dev
      interval: 1m
  values:
    enabled: true
    nameOverride: minio
    mode: standalone
    replicas: 2
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - minio.local
    persistence:
      enabled: true
      size: 10Gi
    existingSecret: minio-secret
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        cpu: "100m"
        memory: "100Mi"
