apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki-stack
spec:
  interval: 1m
#  dependsOn:
#    - name: kube-prometheus-stack
  chart:
    spec:
      version: "2.x"
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
  # https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
  # https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
  values:
    promtail:
      enabled: true
    loki:
      enabled: true
      isDefault: false
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: loki.svc-dev.ink
            paths: []
        tls:
          - secretName: obs-tls
            hosts:
              - loki.svc-dev.ink
      ruler:
        storage:
          type: local
          local:
            directory: /rules
        rule_path: /tmp/scratch
        alertmanager_url: https://alertmanager.svc-dev.ink
        ring:
          kvstore:
            store: inmemory
        enable_api: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          app.kubernetes.io/part-of: kube-prometheus-stack
      config:
        chunk_store_config:
          max_look_back_period: 0s
        table_manager:
          retention_deletes_enabled: true
          retention_period: 12h
