apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
  namespace: itsm-dev
spec:
  interval: 1m
  chart:
    spec:
      version: "18.12.1"
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: itsm-dev
      interval: 1m
  values:
    enabled: true
    nameOverride: "redis"
    architecture: standalone
    global:
      imageRegistry: ""
      redis:
        password: "redis"
    auth:
      enabled: true
      sentinel: false
      password: ""
    master:
      persistence:
        enabled: false
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          cpu: "200m"
          memory: "300Mi"
