- name: 执行 pre-setup 操作
  include_tasks: "{{ playbook_dir }}/roles/docker/keycloak/tasks/pre-setup.yml"

- name: 渲染 .env 配置文件
  template:
    src: "{{ playbook_dir }}/roles/docker/keycloak/templates/.env.j2"
    dest: "{{ playbook_dir }}/roles/docker/keycloak/files/.env"

- name: 执行 create_keystore.sh 脚本
  script: "{{ playbook_dir }}/roles/docker/keycloak/files/create_keystore.sh"
  args:
    chdir: "/home/ubuntu"

- name: 渲染 Docker Compose 配置文件
  template:
    src: "{{ playbook_dir }}/roles/docker/keycloak/templates/docker-compose.yml.j2"
    dest: "{{ playbook_dir }}/roles/docker/keycloak/files/docker-compose.yml"

- name: 启动 Docker Compose 服务
  become: true
  docker_compose:
    project_src: "{{ playbook_dir }}/roles/docker/keycloak"
    files:
      - "{{ playbook_dir }}/roles/docker/keycloak/files/docker-compose.yml"
    restarted: true
    state: present

- name: 执行 post-setup 操作
  include_tasks: "{{ playbook_dir }}/roles/docker/keycloak/tasks/post-setup.yml"
