- name: DeepFlow Agent Upgrade for 区域节点
  hosts: all
  become: true
  gather_facts: false
  vars:
    area: js2
    upgrade_zip_path: ./DeepFlow-Agent-Upgrade-20250523.zip
  roles:
    - deepflow_upgrade

