- hosts: all
  become: true
  vars:
    # Use the inventory hostname for delegation so Ansible
    # applies the correct connection variables
    ops_host: "k8s-1"
    masters:
      - "k8s-1"
    nodes:
      - "k8s-2"
      - "k8s-3"
  roles:
    - roles/vhosts/common/
    - roles/vhosts/ssh-trust/
    - roles/vhosts/gpu-k8s/
