---
- name: setup OpenResty server
  hosts: icp-aliyun
  become: true
  vars:
    domain:
      - name: cn-homepage.svc.plus
        ssl_certificate: /etc/ssl/svc.plus.pem
        ssl_certificate_key: /etc/ssl/svc.plus.rsa.key
      - name: cn-artifact.svc.plus
        ssl_certificate: /etc/ssl/svc.plus.pem
        ssl_certificate_key: /etc/ssl/svc.plus.rsa.key
  roles:
    - roles/vhosts/common/
    - roles/vhosts/ssh-trust/
    - roles/vhosts/OpenResty/
---
- name: setup OpenResty server
  hosts: global-hub
  become: true
  vars:
    domain:
      - name: global-homepage.svc.plus
        ssl_certificate: /etc/ssl/svc.plus.pem
        ssl_certificate_key: /etc/ssl/svc.plus.rsa.key
      - name: global-artifact.svc.plus
        ssl_certificate: /etc/ssl/svc.plus.pem
        ssl_certificate_key: /etc/ssl/svc.plus.rsa.key
  roles:
    - roles/vhosts/common/
    - roles/vhosts/ssh-trust/
    - roles/vhosts/OpenResty/

